# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://StevenJack1.github.io/
date_format: "ordinal"
title: MyNotes
subtitle: "Make the impossible possible, the possible easy and the easy elegant"
description: "严泽凡的个人博客"
keywords: 严泽凡
favicon: /favicon.ico
timezone: Asia/BeiJing
encoding: "utf-8"
source_code: https://github.com/StevenJack1/StevenJack1.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 严泽凡
organization: ThoughtWorks
organization_url: https://www.thoughtworks.com/
location: BeiJing, China
email: 18231550929@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /about/
    label: 关于我

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: StevenJack1
facebook_username: StevenJack
weibo_username: StevenJack
zhihu_username: 严泽凡
twitter_username: StevenJack

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, changyan
comments_provider: disqus

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-82434482-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_language_keywords: [Java, Scala, C Sharp, Python]
skill_web_app_keywords: [javaEE, Spring ,Spring MVC ,JPA , Hibernate , MyBatis, Shiro ,Redis ,Spring Data ,MySql ,ASP.NET ,ASP.NET MVC,Entity Framework]
